import { Router, type IRouter } from "express";
import authRouter from "./auth";
import socialAuthRouter from "./socialAuth";
import healthRouter from "./health";
import versionRouter from "./version";
import dashboardRouter from "./dashboard";
import instructorsRouter from "./instructors";
import classesRouter from "./classes";
import schedulesRouter from "./schedules";
import pricePackagesRouter from "./pricePackages";
import classPricingRouter from "./classPricing";
import bookingsRouter from "./bookings";
import studentsRouter from "./students";
import offersRouter from "./offers";
import notificationsRouter from "./notifications";
import marketingRouter from "./marketing";
import analyticsRouter from "./analytics";
import packageOrdersRouter from "./packageOrders";
import attendanceRouter from "./attendance";
import heroItemsRouter from "./heroItems";
import emailOtpRouter from "./emailOtp";
import adminAuthRouter from "./adminAuth";
import childrenRouter from "./children";
import balletRouter from "./ballet";
import adminBalletRouter from "./adminBallet";
import danceTypesRouter from "./danceTypes";
import checkInRouter from "./checkIn";
import adminCreditsRouter from "./adminCredits";
import myRouter from "./myRoutes";
import appContentRouter from "./appContent";
import instagramRouter from "./instagram";
import reportsRouter from "./reports";

const router: IRouter = Router();

router.use(healthRouter);
router.use(versionRouter);
router.use(authRouter);
router.use(socialAuthRouter);
router.use(emailOtpRouter);
router.use(dashboardRouter);
router.use(analyticsRouter);
router.use(instructorsRouter);
router.use(classesRouter);
router.use(schedulesRouter);
router.use(pricePackagesRouter);
router.use(classPricingRouter);
router.use(bookingsRouter);
router.use(studentsRouter);
router.use(offersRouter);
router.use(notificationsRouter);
router.use(marketingRouter);
router.use(attendanceRouter);
router.use(packageOrdersRouter);
router.use(heroItemsRouter);
router.use(adminAuthRouter);
router.use(childrenRouter);
router.use(balletRouter);
router.use(adminBalletRouter);
router.use(danceTypesRouter);
router.use(checkInRouter);
router.use(adminCreditsRouter);
router.use(myRouter);
router.use(appContentRouter);
router.use(instagramRouter);
router.use(reportsRouter);

export default router;
