import { Router, type IRouter } from "express";
import authRouter from "./auth";
import healthRouter from "./health";
import dashboardRouter from "./dashboard";
import instructorsRouter from "./instructors";
import classesRouter from "./classes";
import schedulesRouter from "./schedules";
import pricePackagesRouter from "./pricePackages";
import bookingsRouter from "./bookings";
import studentsRouter from "./students";
import offersRouter from "./offers";
import notificationsRouter from "./notifications";
import marketingRouter from "./marketing";
import analyticsRouter from "./analytics";
import packageOrdersRouter from "./packageOrders";
import attendanceRouter from "./attendance";
import heroItemsRouter from "./heroItems";
import emailOtpRouter from "./emailOtp";
import adminAuthRouter from "./adminAuth";
import childrenRouter from "./children";
import balletRouter from "./ballet";
import adminBalletRouter from "./adminBallet";
import danceTypesRouter from "./danceTypes";

const router: IRouter = Router();

router.use(healthRouter);
router.use(authRouter);
router.use(emailOtpRouter);
router.use(dashboardRouter);
router.use(analyticsRouter);
router.use(instructorsRouter);
router.use(classesRouter);
router.use(schedulesRouter);
router.use(pricePackagesRouter);
router.use(bookingsRouter);
router.use(studentsRouter);
router.use(offersRouter);
router.use(notificationsRouter);
router.use(marketingRouter);
router.use(attendanceRouter);
router.use(packageOrdersRouter);
router.use(heroItemsRouter);
router.use(adminAuthRouter);
router.use(childrenRouter);
router.use(balletRouter);
router.use(adminBalletRouter);
router.use(danceTypesRouter);

export default router;
