import { Router, type IRouter } from "express";
import authRouter from "./auth";
import socialAuthRouter from "./socialAuth";
import healthRouter from "./health";
import versionRouter from "./version";
import dashboardRouter from "./dashboard";
import instructorsRouter from "./instructors";
import studioBranchesRouter from "./studioBranches";
import adminCalendarRouter from "./adminCalendar";
import adminCalendarOccurrenceRosterRouter from "./adminCalendarOccurrenceRoster";
import classesRouter from "./classes";
import schedulesRouter from "./schedules";
import pricePackagesRouter from "./pricePackages";
import classPricingRouter from "./classPricing";
import classCapacityRouter from "./classCapacity";
import bookingsRouter from "./bookings";
import studentsRouter from "./students";
import promotionsRouter from "./promotions";
import notificationsRouter from "./notifications";
import notificationCampaignsRouter from "./notificationCampaigns";
import marketingRouter from "./marketing";
import analyticsRouter from "./analytics";
import packageOrdersRouter from "./packageOrders";
import attendanceRouter from "./attendance";
import feedbackRouter from "./feedback";
import heroItemsRouter from "./heroItems";
import emailOtpRouter from "./emailOtp";
import adminAuthRouter from "./adminAuth";
import adminActivityLogsRouter from "./adminActivityLogs";
import notificationDeliveryLogsRouter from "./notificationDeliveryLogs";
import childrenRouter from "./children";
import balletRouter from "./ballet";
import adminBalletRouter from "./adminBallet";
import adminBalletPaymentsRouter from "./adminBalletPayments";
import balletCancellationRefundsRouter from "./balletCancellationRefunds";
import adminBalletInstructorsRouter from "./adminBalletInstructors";
import adminBalletClassesRouter from "./adminBalletClasses";
import adminBalletSchedulesRouter from "./adminBalletSchedules";
import adminBalletGroupsRouter from "./adminBalletGroups";
import adminBalletPackagesRouter from "./adminBalletPackages";
import adminBalletPerformancesRouter from "./adminBalletPerformances";
import danceTypesRouter from "./danceTypes";
import checkInRouter from "./checkIn";
import adminAttendanceGatewayRouter from "./adminAttendanceGateway";
import adminCreditsRouter from "./adminCredits";
import myRouter from "./myRoutes";
import appContentRouter from "./appContent";
import instagramRouter from "./instagram";
import reportsRouter from "./reports";
import backgroundMusicRouter from "./backgroundMusic";
import classReminderSettingsRouter from "./classReminderSettings";
import financeRouter from "./finance";
import financeBackfillBatchesRouter from "./financeBackfillBatches";
import catalogueReadinessRouter from "./catalogueReadiness";
import packageRefundsRouter from "./packageRefunds";
import adminRoomReservationsRouter from "./adminRoomReservations";

const router: IRouter = Router();

router.use(healthRouter);
router.use(versionRouter);
router.use(authRouter);
router.use(socialAuthRouter);
router.use(emailOtpRouter);
router.use(dashboardRouter);
router.use(analyticsRouter);
router.use(instructorsRouter);
router.use(studioBranchesRouter);
router.use(adminCalendarRouter);
router.use(adminCalendarOccurrenceRosterRouter);
router.use(classesRouter);
router.use(schedulesRouter);
router.use(pricePackagesRouter);
router.use(classPricingRouter);
router.use(classCapacityRouter);
router.use(bookingsRouter);
router.use(studentsRouter);
router.use(promotionsRouter);
router.use(notificationsRouter);
router.use(notificationCampaignsRouter);
router.use(marketingRouter);
router.use(attendanceRouter);
router.use(feedbackRouter);
router.use(packageOrdersRouter);
router.use(heroItemsRouter);
router.use(adminAuthRouter);
router.use(adminActivityLogsRouter);
router.use(notificationDeliveryLogsRouter);
router.use(childrenRouter);
router.use(balletRouter);
router.use(adminBalletRouter);
router.use(adminBalletPaymentsRouter);
router.use(balletCancellationRefundsRouter);
router.use(adminBalletInstructorsRouter);
router.use(adminBalletClassesRouter);
router.use(adminBalletSchedulesRouter);
router.use(adminBalletGroupsRouter);
router.use(adminBalletPackagesRouter);
router.use(adminBalletPerformancesRouter);
router.use(danceTypesRouter);
router.use(checkInRouter);
router.use(adminAttendanceGatewayRouter);
router.use(adminCreditsRouter);
router.use(myRouter);
router.use(appContentRouter);
router.use(instagramRouter);
router.use(reportsRouter);
router.use(backgroundMusicRouter);
router.use(classReminderSettingsRouter);
router.use(catalogueReadinessRouter);
router.use(packageRefundsRouter);
router.use(adminRoomReservationsRouter);
// Finance Department (Phase 1) — read-only aggregation over the existing
// operational tables. Registered last; it adds no mutation routes.
router.use(financeRouter);

// Finance Phase 2D-2 — historical backfill batch control (metadata/status
// only). No route in this router can write a Finance/source table.
router.use(financeBackfillBatchesRouter);

export default router;
