-- Migration 0050: Ballet Applications Active Uniqueness (Phase A / P0-8a, P0-8b)
--
-- Guarantees, at the database level, that a child (or a not-yet-linked
-- manual/walk-in identity) can only have ONE open (non-rejected,
-- non-cancelled) ballet application at a time. Enforced via two separate
-- partial unique indexes rather than a single combined one, because the
-- two cases (linked child vs. manual submission) key on entirely different
-- columns and must remain independently diagnosable.
--
-- Both indexes were generated by `pnpm --filter @workspace/db run generate`
-- from the uniqueIndex(...).where(...) definitions added to
-- lib/db/src/schema/balletApplications.ts, and its output matched the spec
-- exactly — nothing about the CREATE UNIQUE INDEX statements themselves was
-- hand-altered. What drizzle-kit cannot generate is the pair of preflight
-- checks below: each index gets its OWN independent DO $$ block, run BEFORE
-- its own CREATE UNIQUE INDEX, so a violation on one constraint is reported
-- on its own and does not block the other constraint from being checked/
-- created if its own data is clean.
--
-- Each preflight predicts Postgres's real unique-index semantics: a row
-- with any NULL among the indexed columns can never collide with another
-- row (NULL is never "equal" to anything, including another NULL, absent
-- NULLS NOT DISTINCT — not used here), so the manual-identity preflight
-- only flags rows where parent_student_id AND child_birthday are BOTH
-- present, matching what the index itself would actually reject.

-- ---------------------------------------------------------------------------
-- Preflight 1/2 — ballet_applications_active_per_child
-- Aborts ONLY this index's creation if violated; does not touch the
-- manual-identity index below.
-- ---------------------------------------------------------------------------
DO $$
DECLARE
  conflict_count integer;
BEGIN
  SELECT count(*) INTO conflict_count FROM (
    SELECT "child_id"
    FROM "ballet_applications"
    WHERE "child_id" IS NOT NULL
      AND "status" NOT IN ('rejected', 'cancelled')
    GROUP BY "child_id"
    HAVING count(*) > 1
  ) "conflicts";

  IF conflict_count > 0 THEN
    RAISE EXCEPTION 'Aborting ballet_applications_active_per_child (migration 0050): % child_id value(s) have more than one non-terminal (status not in rejected/cancelled) ballet_applications row. Inspect with: SELECT child_id, array_agg(id) FROM ballet_applications WHERE child_id IS NOT NULL AND status NOT IN (''rejected'',''cancelled'') GROUP BY child_id HAVING count(*) > 1;', conflict_count;
  END IF;
END $$;

CREATE UNIQUE INDEX "ballet_applications_active_per_child" ON "ballet_applications" USING btree ("child_id") WHERE "ballet_applications"."child_id" is not null and "ballet_applications"."status" not in ('rejected','cancelled');--> statement-breakpoint

-- ---------------------------------------------------------------------------
-- Preflight 2/2 — ballet_applications_active_per_manual_identity
-- Independent of the block above: if THIS check fails, it aborts only this
-- index's creation — the per_child index above has already been created by
-- this point and is unaffected.
-- ---------------------------------------------------------------------------
DO $$
DECLARE
  conflict_count integer;
BEGIN
  SELECT count(*) INTO conflict_count FROM (
    SELECT "parent_student_id", lower(trim("child_name")) AS norm_child_name, "child_birthday"
    FROM "ballet_applications"
    WHERE "child_id" IS NULL
      AND "status" NOT IN ('rejected', 'cancelled')
      AND "parent_student_id" IS NOT NULL
      AND "child_birthday" IS NOT NULL
    GROUP BY "parent_student_id", lower(trim("child_name")), "child_birthday"
    HAVING count(*) > 1
  ) "conflicts";

  IF conflict_count > 0 THEN
    RAISE EXCEPTION 'Aborting ballet_applications_active_per_manual_identity (migration 0050): % manual-identity (parent_student_id, child_name, child_birthday) group(s) have more than one non-terminal ballet_applications row. Inspect with: SELECT parent_student_id, lower(trim(child_name)) AS name, child_birthday, array_agg(id) FROM ballet_applications WHERE child_id IS NULL AND status NOT IN (''rejected'',''cancelled'') AND parent_student_id IS NOT NULL AND child_birthday IS NOT NULL GROUP BY parent_student_id, lower(trim(child_name)), child_birthday HAVING count(*) > 1;', conflict_count;
  END IF;
END $$;

CREATE UNIQUE INDEX "ballet_applications_active_per_manual_identity" ON "ballet_applications" USING btree ("parent_student_id",lower(trim("child_name")),"child_birthday") WHERE "ballet_applications"."child_id" is null and "ballet_applications"."status" not in ('rejected','cancelled');
